version: '3'

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 30719104
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 30719104
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 30719104

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - nginx
